<?php

namespace AppBundle\Repository;

/**
 * DealCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
